### ISSUE TITLE
Publish to Hashnode not being in Draft

### ISSUE THREAD

**Issue by vanessahjerpe** [shahednasser/cross-post#1]
I've tried publishing to all of them and it seems to work except for Hashnode. That one will always instantly be published and not put in to draft.

Is this a bug?

**Comment by shahednasser** [comment]
No, it's not a bug. Unfortunately, Hashnode's API currently does not allow publishing as a draft in their API. 

The only thing you can do is publish it as "Hidden from hashnode" however, I feel like that doesn't even work as it should either.

If Hashnode adds that as part of their API, I'll make sure to amend this tool based on it.
