### ISSUE TITLE
urlencodes less than and greater than symbols

### ISSUE THREAD

**Issue by rberger** [shahednasser/cross-post#14]
When I ran cross-post from a Wordpress source to Medium, it seems to have url encoded all the `<` and `>` characters. I had to manually clean them all up in the medium post before publishing.

I haven't tried it for other targets

**Comment by shahednasser** [comment]
Hi @rberger 

do you mean the symbols in the content of the article are being encoded?

All articles are transformed into markdown as it is required to submit the article on all platforms. Maybe we can look into adding something to normalize that. However, I haven't encountered an issue like that so far.

**Comment by rberger** [comment]
Yes it definitely was doing it for content that was in a code block. I think it might have been doing it for content just in regular text.

**Comment by shahednasser** [comment]
Hello @rberger this issue has been resolved now as the markdown converter library has been changed and code blocks are handled better now.
