### ISSUE TITLE
RequestError: unable to verify the first certificate

### ISSUE THREAD

**Issue by hussaincode** [shahednasser/cross-post#19]
Getting this error while uploading the blog using cross-post.
my command - cross-post run https://hussaincodes.in/registrationlogin-system-using-spring-boot-and-spring-security -p dev hashnode

**Comment by shahednasser** [comment]
Hi @hussaincode , does this error occur for both platforms? If you run it just for dev or just for hashnode, does it occur eitherway?

**Comment by hussaincode** [comment]
yes it occurred with both the platform

**Comment by shahednasser** [comment]
Ok so I first tested your command and I didn't get any issues, so I can't reproduce it. However, I looked online for this error and found this:

https://github.com/sindresorhus/got/issues/675

Based on the fix suggested I pushed a new version with the fix. Can you try updating the tool then running the same command?

**Comment by hussaincode** [comment]
Thanks @shahednasser it's working fine now 👍
