### ISSUE TITLE
Posting from hashnode to medium is not working

### ISSUE THREAD

**Issue by AlessandroVol23** [shahednasser/cross-post#21]
Hi 👋🏽

love your CLI! 

Somehow I can't cross-post this article https://sandro.volpee.de/aws-lambda-interview-questions to medium without a lot of gibberish and CSS to appear.

I've run the command: `cross-post run https://sandro.volpee.de/aws-lambda-interview-questions -p medium`

Any idea why that happens? I configured cloudinary for the images. 

<img width="727" alt="image" src="https://user-images.githubusercontent.com/19362086/156590508-6cfd1ac5-6b6a-4cd4-8a67-46565bee0fdf.png">

**Comment by shahednasser** [comment]
Hi @AlessandroVol23 this issue has been resolved you just need to update the tool. However, I do recommend you set the `selector` config to `#post-content-wrapper` as by default this tool uses the selector `article` to grab the article, and hashnode has a bunch of other elements that are inside the Article element. You'll probably have to set the image selector and the title selector as well.

**Comment by AlessandroVol23** [comment]
All right thanks! I'll try that :)
