### ISSUE TITLE
Add reset config command

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/cross-post#22]
Add a command to reset the config. It can accept the name of a config or if no name provided then the entire config (with the exception of the platforms' API keys should be reset).

This can be helpful for development and testing.

**Comment by HarshaVardhanNakkina** [comment]
> with the exception of the platforms' API keys should be reset

could you please explain this a little bit more? I want to contribute to this issue

**Comment by HarshaVardhanNakkina** [comment]
I opened a pull request here #23 
- I refactored configuring platforms into sub-commands
- resetting configuration is also made into a sub-command under `config` command
I hope I did some good job, please let me know if you need any changes.
