### ISSUE TITLE
No commands for Windows

### ISSUE THREAD

**Issue by Shaan3110** [shahednasser/cross-post#29]
I am a **Windows** user and while going through various blogs I got redirected here to be the solution I wanted for my cross-posting. But sadly there are no commands for *windows* machine even not in the readme. And also no draft over how to get the thing done if someone is on that machine.

It's really needy as even today the maximum market comes under **Windows** and not drafting a command to configure the same is really not justified for any project.

It's a request to please fix this issue so that the project can be useful for everyone.

**Comment by shahednasser** [comment]
Hello @Shaan3110 thank you for reporting this issue. Unfortunately, I'm not able to work on this issue as I don't have a windows machine.

Can you report the issue that you run into when using this tool on Windows?

**Comment by Omar8345** [comment]
I use Windows and it works properly 🙌, you can try WSL

**Comment by shahednasser** [comment]
@Omar8345 does it work properly without WSL?

**Comment by Omar8345** [comment]
@shahednasser, yes.

**Comment by Omar8345** [comment]
@Shaan3110 You just have to get `npm` installed and run this command: `npm i -g cross-post-blog`

And then use the other configuration commands, etc. as normal.
