### ISSUE TITLE
Add Option for Main Image Selector

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/cross-post#3]
Currently, when getting an article from a URL, the main image is just the first image inside the `<article>` tag. We need to add an option for the `run` command that accepts the selector of the main image, or allow it to be set by default using the `config` command, then using the value set in the `run` command.

**Comment by AlessandroVol23** [comment]
Yes, I face the same issue. Any way to overcome this issue to post an article anyway?

**Comment by shahednasser** [comment]
Hi @AlessandroVol23 , I'm gonna try to take some time throughout this week to resolve this. Unfortunately, I've been busy and unable to maintain this project.

If you would like to contribute that would be of great help.

**Comment by shahednasser** [comment]
This issue has now been resolved. New options have been added to specify the image selector and more. @AlessandroVol23 I suggest you update the tool, check the README then try again.
