### ISSUE TITLE
Error posting to Hashnode

### ISSUE THREAD

**Issue by abhirockzz** [shahednasser/cross-post#43]
Hello, I see this error while trying to cross post to Hashnode. It's probably due to an updated API? Or, am I missing something? Would appreciate your help!

`Error: Error occured while cross posting to Hashnode: Variable "$input" got invalid value { title: "this is a test blog", contentMarkdown: "# this is a test blog", tags: [] }; Field "isPartOfPublication" of required type "PublicationDetails!" was not provided.`

**Comment by palmerusaf** [comment]
@abhirockzz I think you're right there must have been and update to the API. I was able to get it working in pull request #44.
